# FROM node:lts-alpine3.22

# WORKDIR /app
# COPY package*.json ./

# RUN npm install
# COPY . .

# EXPOSE 3000  

# CMD ["npm", "start"]

FROM nginx:alpine

COPY . /usr/share/nginx/html

EXPOSE 3000

