services:
  # ----------------------------------------------------------------------- SQL -----------------------------------------------------------------------
  mysql_db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: e-todo
      MYSQL_ROOT_PASSWORD: TonMotDePasse
      MYSQL_USER: user
      MYSQL_PASSWORD: TonMotDePasse

    volumes:
      - ./e-todo.sql:/docker-entrypoint-initdb.d/e-todo.sql

    networks:
      - back

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

    depends_on:
      - mysql_db

  # ----------------------------------------------------------------------- SQL -----------------------------------------------------------------------

  # ----------------------------------------------------------------------- BACK -----------------------------------------------------------------------

  backend:
    build: ./backend
    container_name: backend_etodo
    ports:
      - "4000:4000"

    networks:
      - back

    depends_on:
      - mysql_db
  # ----------------------------------------------------------------------- BACK -----------------------------------------------------------------------

  # ----------------------------------------------------------------------- FRONT -----------------------------------------------------------------------
  frontend:
    build: ./frontend
    container_name: frontend_etodo
    ports:
      - "3000:3000"

    depends_on:
      - backend
# ----------------------------------------------------------------------- FRONT -----------------------------------------------------------------------

networks:
  back:
    driver: bridge
