services:
  database:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - ./e-todo.sql:/docker-entrypoint-initdb.d/e-todo.sql
    networks:
      - back
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - back
    depends_on:
      - database

  backend:
    build: ./backend
    container_name: backend_etodo
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - back

  frontend:
    build: ./frontend
    container_name: frontend_etodo
    ports:
      - "3000:80"
    networks:
      - back

networks:
  back:
    driver: bridge